### ISSUE TITLE
The order of output in two different ways.

### ISSUE THREAD

**Issue by IshaLohan** [bvanderbeek/TauP.jl#2]
It is not exactly an issue, but a matter of convenience. It is clearly mentioned in README that when using the code, 
`julia> using TauP
julia> TimeTauP = taup_time(["P","S"], 55.0, 100.0; model = "iasp91", verbose = true)`
 in the output, the third column is the Take-off angle in the table. 

```
>  Phase Name   Travel-time (s)   Ray Param (s/deg)   Takeoff (deg)   Incident (deg)
>  ---------------------------------------------------------------------------------
>  P            560.843           7.202               31.98           22.07         
>  S            1015.837          13.365              33.27           23.82
```

But while using the 'lower-level syntax designed for single-phase calculations',
`julia> TimeObj = buildTimeObj("prem") # Build TauP Time object for PREM model
julia> set_taup_phase!(TimeObj, "P") # Set calculation parameters
julia> set_taup_source_depth!(TimeObj, 100.0)
julia> set_taup_receiver_depth!(TimeObj, 0.0)
julia> t, p, i, j = taup_time!(TimeObj, 55.0) # Call taup_time`

this function returns 4 values in which the third output is the Incidence angle. But the first table it is already so appealing (as humans intend to look more at tables and figures than text) that the incidence angle can be mistaken for the take-off angle in this code after looking at the table the first two output remains the same.

Apart from the above, this wrapper is great and very helpful. Everything is working fine. Thanks!

**Comment by bvanderbeek** [comment]
Hi @IshaLohan ,
Thanks for the suggestion! I agree that the output of taup_time! would be cleaner and more intuitive if it followed the table. I'll update this in the next days. Glad you've found the package useful otherwise.

**Comment by bvanderbeek** [comment]
Updated taup_time! output order and the readme and examples to reflect the change.

The TauP package in the Julia registry will not be updated for a while so if you want to use this version, download directly from GitHub via, `Pkg.clone("https://github.com/bvanderbeek/TauP.jl.git")`
